INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('下载路径', '/music', 'music.download.path', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('忽略伴奏', 'true', 'music.ignore.accompaniment', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('禁止重复下载', 'true', 'music.override.download', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('初始化检查未下载', 'true', 'music.init.download', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('同时下载数量', '8', 'music.download.size', 'number', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('强制匹配专辑下歌手', 'true', 'music.strong.match.album.singer', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('专辑歌手统一（多人演唱仅保存下载时查询的歌手）', 'true', 'music.album.singer.unity', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('登录账号', 'admin', 'system.username', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('登录密码', 'admin', 'system.password', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('默认下载类型', 'flac', 'music.download.type', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('酷我flac类型', '2000kflac', 'plug.kw.flac.type', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('酷我mp3类型', '320kmp3', 'plug.kw.mp3.type', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('咪咕flac类型', 'ZQ', 'plug.mg.flac.type', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('咪咕mp3类型', 'HQ', 'plug.mg.mp3.type', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('使用aria2下载', 'true', 'plug.download.type', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQvip基础url', 'http://127.0.0.1', 'plug.qqvip.baseurl', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQvip插件是否启用开关', 'false', 'plug.qqvip.open', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQVIP插件同步开关（开启后才能开启其他同步功能）', 'false', 'plug.qqvip.sync', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQVIP插件同步我喜欢的歌曲', 'false', 'plug.qqvip.synclikesong', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQVIP插件同步我喜欢的专辑', 'false', 'plug.qqvip.synclikealbum', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQVIP插件同步收藏和自建歌单', 'false', 'plug.qqvip.syncplaylist', 'switch', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQVIP插件排除指定名称的歌单多个,（半角,）分割（不会同步的歌单名称）', '多个,分割', 'plug.qqvip.syncplaylistexclude', 'input', 'Y');
INSERT INTO `sq_config` (`config_name`, `config_value`, `config_key`, `type`, `config_show`) VALUES ('QQ号', '123456', 'plug.qqvip.qq', 'input', 'Y');
-- 网易的暂时不用 以后再说
-- INSERT INTO sq_config ( config_name, config_value, config_key, type, config_show) VALUES ( '网易基础地址', 'https://netease.happyking.top', 'plug.netease.baseurl', 'input','Y');
-- INSERT INTO sq_config ( config_name, config_value, config_key, type, config_show) VALUES ( '网易开启匿名登录', 'anonymousLogin', 'plug.netease.anonymousLogin', 'switch','Y');
-- INSERT INTO sq_config ( config_name, config_value, config_key, type, config_show) VALUES ( '网易cookieUrl', '/register/anonimous', 'plug.netease.cookieUrl', 'input','Y');
-- INSERT INTO sq_config ( config_name, config_value, config_key, type, config_show) VALUES ( '网易cookie值（写了就不用匿名登陆了）', '', 'plug.netease.cookie', 'input','Y');
-- INSERT INTO sq_config ( config_name, config_value, config_key, type, config_show) VALUES ( '网易下载链接', 'https://csm.sayqz.com/api/?type=apiSongUrlV1&level=#{level}&id=#{id}', 'plug.netease.downloadUrl', 'input','Y');
